name: CI/CD backend in Docker
on:
  push:
    branches:
      - 5-CICD-fullCorrection
    paths:
      - 'BACK/API.Library/**'
      - '.github/workflows/workflow-backend.yaml'

defaults:
  run:
    working-directory: ./BACK/API.Library

jobs:
  api-library:
    runs-on: ubuntu-latest
    env:
      SpecFlowDirectory: Tests/Library.Tests.Specs
      SpecFlowTestAssemblyPath: bin/Release/net6.0/Library.Tests.Specs.dll
      SpecFlowTestExecutionPath: bin/Release/net6.0/TestExecution.json
    steps:
      - name : Checkout repository
        uses: actions/checkout@v3

      - name : Set up environment dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Build all projects
        run: dotnet build -c Release
        shell: bash

      - name: Run tests
        run: dotnet test --no-build -c Release -v minimal
        shell: bash

      - name: Generate SpecFlow LivingDoc
        run: |
          dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
          livingdoc test-assembly $SpecFlowDirectory/$SpecFlowTestAssemblyPath -t $SpecFlowDirectory/$SpecFlowTestExecutionPath -o LivingDoc.html
        shell: bash

      - name : Publish LivingDoc
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: SpecflowTestResults
          path: BACK/API.Library/LivingDoc.html

      - name: Get git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - id: nextversion
        name: next release version
        uses: jenkins-x-plugins/jx-release-version@v2.6.1

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.nextversion.outputs.version }}
          generate_release_notes: true
          target_commitish: ${{ github.ref }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with tag github & tag latest
        uses: docker/build-push-action@v3
        with:
          context: ./BACK/API.Library
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/back_vault:${{ steps.nextversion.outputs.version }}, ${{ secrets.DOCKER_USERNAME }}/back_vault:latest
