name: CI/CD backend
on:
  push:
    branches:
      - main
    paths:
      - 'BACK/API.Library/**'
      - '.github/workflows/workflow-backend.yaml'

defaults:
  run:
    working-directory: ./BACK/API.Library

jobs:
  api-library:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository
        uses: actions/checkout@v3
